# general settings
input_directory: 'input/'
output_directory: 'output/'

seed: 1996

# image settings
width: 32
height: 32
depth: 3

# training settings
epochs: 10
learning_rate: 0.001
batch_size: 256
validation_size: 0.3
verbose: 1



# GUI settings
