# general settings
input_directory: "input/"
output_directory: "output/"
manual_file: "manual.pdf"
document_file: "documentation.pdf"
github_code: "https://github.com/pfijen/ProjectOBP"

seed: 1991

# image settings
width: 32
height: 32
depth: 3

# training settings
epochs: 3
learning_rate: 0.001
momentum: 0.75
batch_size: 64
validation_size: 0.3
verbose: 1

# GUI settings
model_path: "models/model.h5"
plots_path: "plots/"
