# general settings
input_directory: 'input/'
output_directory: 'output/'

seed: 1991

# image settings
width: 32
height: 32
depth: 3

# training settings
epochs: 10
learning_rate: 0.005
batch_size: 512
validation_size: 0.3
verbose: 1


# GUI settings
